services:
  db:
    ports:
      - "3306:3306"
    build:
      context: ./
      args:
        DB_USERNAME: ${DB_USERNAME}
    image: db
    volumes:
      - $(PWD):/var/lib/mysql
    env_file:
      - .env