services:
  db:
    ports:
      - "3306:3306"
    build:
      context: ${PWD}
      args:
        DB_USERNAME: ${DB_USERNAME}
    image: db
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: your_secure_password
      MARIADB_ROOT_HOST: '%'
