services:
  db:
    image: mariadb
    ports:
      - "8000:3306"
    env_file:
        - ./database/.env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    # build:
    #   context: ./database
    #   args:
    #     DB_USERNAME: ${DB_USERNAME}
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app
  nginx:
    # ports:
    #   - "8080:80"
    build:
      context: ./nginx
    image: nginx:alpine3.24
    container_name: nginx
    networks:
      - app
    volumes:
      - src:/var/www/html
      # - public_files:/var/www/html/public
  hot-reload:
    image: hot-reload
    container_name: hot-reload
    build:
      context: ./dev/hot-reload
    depends_on:
      - nginx
    ports:
      - "8080:3000"
    volumes:
      - src:/var/www/html
    networks:
      - app
  php-fpm:
    # image: php:8-fpm
    image: php-fpm
    build:
      context: ./php-fpm
    volumes:
      - src:/var/www/html
    container_name: php-fpm
    networks:
      - app
    
volumes:
  db_data:
  src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src
  # public_files:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./public

networks:
  app:
    driver: bridge
    